### PR TITLE
do not rely on `symbol` for filtering out `redirect`s from loader data

### LINKED ISSUE #12615: 'redirectSymbol' introduced in #12527 causes type error
### I'm using React Router as a...

framework

### Reproduction

Run `tsc`

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 139.30 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: 9.15.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.1.1
```

### Used Package Manager

pnpm

### Expected Behavior

No type errors

### Actual Behavior

Received error:

```
error TS4058: Return type of exported function has or is using name 'redirectSymbol' from external module "/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/route-data-aSUFWnQ6" but cannot be named.

export async function loader({ request, context }: Route.LoaderArgs) {
```

### PR DESCRIPTION
**Pull request by pcattori**
Fixes #12615

### CODE REVIEW

**Comment by brendanfmartin** [comment]
Thanks so much @pcattori. I started my migration from Remix to RR7 yesterday and I'm glad the issues are actively being addressed.

How long does it take from merge to a release?
