### ISSUE TITLE
[Bug]: `useActionData` returns raw `Response` when using polyfilled `fetch`

### ISSUE THREAD

**Issue by hovsater** [remix-run/react-router#9722]
### What version of React Router are you using?

6.4.5

### Steps to Reproduce

In a standard [CRA](https://create-react-app.dev) environment,  `fetch` is being polyfilled by [fetch](https://github.com/github/fetch) when running tests. Unfortunately, the polyfill does not implement `.body`, thus the new check introduced in https://github.com/remix-run/react-router/pull/9690 fail and `useActionData` returns the raw Response instead.

### Expected Behavior

I expect `useActionData` to always unwrap the `Response` body and give back the actual JSON.

### Actual Behavior

Since the polyfill does not implement `.body`, `typeof value.body !== "undefined"` always fail and the response is not unwrapped as expected. Instead, the raw `Response` is returned by `useActionData`.

**Comment by brophdawg11** [comment]
Hm, I'm not sure we want to alter the router code to support a non-spec-compliant `fetch` polyfill just for testing purposes.  Remix maintains it's own polyfill that aims to align as closely with the spec as possible, could you solve the issue by adding [something like this](https://github.com/remix-run/react-router/blob/main/packages/router/__tests__/setup.ts) to your jest setup files?

Or potentially just call `installGlobals()` from `@remix-run/node`

**Comment by hovsater** [comment]
@brophdawg11 I think switching to a different polyfill makes sense in the general case. However, we haven't explicitly opted in to using [fetch](https://github.com/github/fetch). It's being [injected automatically](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-scripts/scripts/utils/createJestConfig.js#L33) by [CRA](https://create-react-app.dev). Thus, I'm assuming this will break any application created using CRA that have not yet [ejected](https://create-react-app.dev/docs/available-scripts/#npm-run-eject).

**Comment by juha-finlabs** [comment]
Affects me as well. I tried to add those polyfills from `@remix-run/web-fetch`, but it did not work since original polyfill uses different `URL` implementation (or so I understood):

```
TypeError: Invalid URL: /some/endpoint
at new URLImpl (/some_project/node_modules/jest-environment-jsdom/node_modules/whatwg-url/dist/URL-impl.js:21:13)
at Object.exports.setup (/some_project/node_modules/jest-environment-jsdom/node_modules/whatwg-url/dist/URL.js:54:12)
at new URL (/some_project/node_modules/jest-environment-jsdom/node_modules/whatwg-url/dist/URL.js:107:22)
at new Request (/some_project/node_modules/@remix-run/web-fetch/src/request.js:78:16)
at /some_project/node_modules/@remix-run/web-fetch/src/fetch.js:42:19
at new Promise (<anonymous>)
at fetch (/some_project/node_modules/@remix-run/web-fetch/src/fetch.js:40:9)
```

**Comment by brophdawg11** [comment]
@hovsater Have you checked with the CRA folks to see if they're open to using a spec-compliant fetch polyfill?  That feels like the proper avenue here to me, I don't know that we want to propagate non-spec-compliant support into react-router due to a choice made by CRA.

**Comment by hovsater** [comment]
I have not. I'll do that as well to start a discussion on their side. 🙂

**Comment by hovsater** [comment]
FYI: I'ved opened https://github.com/facebook/create-react-app/issues/12913 over at [facebook/create-react-app]( https://github.com/facebook/create-react-app).

**Comment by brophdawg11** [comment]
Thanks @hovsater!  I'll keep an eye over there as well!
