### ISSUE TITLE
[Bug]: generatePath() error when upgrading react-router-dom

### ISSUE THREAD

**Issue by jafin** [remix-run/react-router#8027]
### What version of React Router are you using?

5.3

### Steps to Reproduce

Upgraded package from react-router-dom 5.2 to 5.3
Recompiled project. (Create react app)

Error received in react-router on page using `generatePath`

```
compile is not a function
```

To correct:

```bash
npm i path-to-regexp@2.4.0  
```

Using `path-regexp` version `6.2.0` would result in an error

```js
./node_modules/react-router/esm/react-router.js
Attempted import error: 'path-to-regexp' does not contain a default export (imported as 'pathToRegexp').
```

Suggest either pinning path-to-regexp to 2.4  to fix to work with 6.2

### Expected Behavior

executing function `generatePath` should work as expected.
Issue is same as reported in #7922, but that issue is closed.

### Actual Behavior

Error received in react-router on page using `generatePath`

```
compile is not a function
```

**Comment by timdorr** [comment]
Newer versions of path-to-regexp have breaking changes and feature removals, so it's not as simple as just upgrading to the newer API.

[We depend on path-to-regexp@1.7](https://github.com/remix-run/react-router/blob/main/packages/react-router/package.json#L44), so you don't need to install a specific version. It's already provided and will be installed as a sub-dependency of the react-router module (assuming you don't override resolution)
