### ISSUE TITLE
[Bug]: "Cannot find module './index' or its corresponding type declarations" in react-router-dom/server.d.ts

### ISSUE THREAD

**Issue by neoGeneva** [remix-run/react-router#11509]
### What version of React Router are you using?

6.23.0

### Steps to Reproduce

Install react-router-dom in a TS project, and attempt to compile the project.

### Expected Behavior

The project compiles.

### Actual Behavior

An error is raised during compilation: 

```
node_modules/react-router-dom/server.d.ts:3:58 - error TS2307: Cannot find module './index' or its corresponding type declarations.

3 import type { FutureConfig, Location, RouteObject } from "./index";
                                                           ~~~~~~~~~
```

**Comment by faergeek** [comment]
In a previous version this import looked like this:

```typescript
import type { FutureConfig, Location, RouteObject } from "react-router-dom";
```

And there are no recent changes in source here. So I guess something has changed in a build process maybe?

**Comment by timdorr** [comment]
Broken by #11358

**Comment by brophdawg11** [comment]
This is resolved by #11514 and will be available in the next release
