### ISSUE TITLE
[Bug]: navigator.block() is not a function anymore

### ISSUE THREAD

**Issue by dragos99** [remix-run/react-router#9262]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

```
const navigator = useContext(UNSAFE_NavigationContext).navigator;
navigator.block()
```

### Expected Behavior

In version 6.3 this function was working.

### Actual Behavior

navigator.block() throws an error that it is not a function anymore.

**Comment by MarksCode** [comment]
I created a workaround for `v6.4`:

https://gist.github.com/MarksCode/64e438c82b0b2a1161e01c88ca0d0355

**Comment by timdorr** [comment]
`NavigationContext` is marked as `UNSAFE_` because it's not a public API and is subject to change at any time. 

I believe we are moving away from implementing navigation blocking right now because it interferes with async rendering. We don't yet have a safe way to provide for blocking the navigation while allowing for async flows.

**Comment by dragos99** [comment]
This makes the entire library unusable...

**Comment by DavidHenri008** [comment]
@MarksCode Your solution is gret, but it seams to have a little error on line 33, it should be ```if (when)```.
Also this solution does not work with hash urls (www.something.com/#page1)

**Comment by MarksCode** [comment]
@DavidHenri008 Think you're right. Fixed it.

**Comment by ioev** [comment]
@MarksCode Any chance this could also handle "back/forward button" navigation?

**Comment by victorlitvinenko** [comment]
@MarksCode 's solution is great, thanks! 
But it doesn't handle "back/forward button" navigation.

**Comment by eryilmazyasin** [comment]
Okey, we understood that the navigation block is removed. Is there an alternative way to do this you recommended? As you can see we're struggling :) @timdorr

**Comment by crates** [comment]
The lack of this feature is causing tests that worked in Cypress to break when v6.4.x of React Router is installed. It would be great if either React Router could bring this back, or Cypress could update their stuff, bc my tests are broken now.

**Comment by brophdawg11** [comment]
Please refer to https://github.com/remix-run/react-router/issues/8139#issuecomment-1262630360 for our update on `navigator.block`
