### ISSUE TITLE
[Bug]: navigator.block is not a function

### ISSUE THREAD

**Issue by atarek12** [remix-run/react-router#9272]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

I was consuming the navigator from `UNSAFE_NavigationContext` context to block the user navigation in some situations.

After upgrading to `v6.4.0`, I found that the block function was removed from the navigator, is it in purpose? and if so, how can we do such a thing as since version-6, `react-router-dom` removed the `Prompt` component and `usePrompt` hook as discussed in this [issue](https://github.com/remix-run/react-router/issues/8139) ?

### Expected Behavior

get back the `navigator.block()` function to life or provide a replacement for it 

### Actual Behavior

I do not find the navigator.block() function and the whole project crash

**Comment by timdorr** [comment]
Duplicate of #9262

**Comment by atarek12** [comment]
@timdorr I think it is not duplicate, as it was working in `v6.3.0`

**Comment by timdorr** [comment]
That issue is discussing this exact same thing (missing navigator.block) in the exact same version (6.4.0).

**Comment by atarek12** [comment]
Sorry, my bad.
