### ISSUE TITLE
'redirectSymbol' introduced in #12527 causes type error

### ISSUE THREAD

**Issue by dantrain** [remix-run/react-router#12615]
### I'm using React Router as a...

framework

### Reproduction

Run `tsc`

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 139.30 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: 9.15.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.1.1
```

### Used Package Manager

pnpm

### Expected Behavior

No type errors

### Actual Behavior

Received error:

```
error TS4058: Return type of exported function has or is using name 'redirectSymbol' from external module "/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/route-data-aSUFWnQ6" but cannot be named.

export async function loader({ request, context }: Route.LoaderArgs) {
```

**Comment by penspinner** [comment]
I am also encountering this TypeScript issue. This error occurs when any functions return a redirect call.

Here is my related Discord message + thread: https://discord.com/channels/770287896669978684/1319889604211511384.

Here are my TypeScript configs:

tsconfig.json
```json
{
    "files": [],
    "references": [{ "path": "./tsconfig.node.json" }, { "path": "./tsconfig.vite.json" }],
    "compilerOptions": {
        "forceConsistentCasingInFileNames": true,
        "isolatedModules": true,
        "skipLibCheck": true,
        "strict": true,
        "noEmit": true,
        "paths": {
            "~/*": ["./app/*"]
        }
    }
}
```
tsconfig.node.json
```json
{
    "extends": "./tsconfig.json",
    "include": [
        "react-router.config.ts",
        "tailwind.config.ts",
        "vite.config.ts",
        "vitest.workspace.ts",
        "prisma/**/*.ts"
    ],
    "compilerOptions": {
        "composite": true,
        "strict": true,
        "types": ["node"],
        "lib": ["ES2022"],
        "target": "ES2022",
        "module": "NodeNext",
        "moduleResolution": "NodeNext"
    }
}
```
tsconfig.vite.json
```json
{
    "extends": "./tsconfig.json",
    "include": [
        ".react-router/types/**/*",
        "app/**/*",
        "app/**/.server/**/*",
        "app/**/.client/**/*",
        "server/**/*",
        "env.d.ts",
        "tests/**/*.ts",
        "types.ts"
    ],
    "compilerOptions": {
        "composite": true,
        "lib": ["DOM", "DOM.Iterable", "ES2022"],
        "types": ["vite/client"],
        "target": "ES2022",
        "module": "ES2022",
        "moduleResolution": "bundler",
        "jsx": "react-jsx",
        "baseUrl": ".",
        "rootDirs": [".", "./.react-router/types"],
        "typeRoots": ["public/node_modules/@types", "./node_modules"],
        "esModuleInterop": true,
        "resolveJsonModule": true
    }
}
```

**Comment by penspinner** [comment]
@pcattori Likely has something to do with this PR here: https://github.com/remix-run/react-router/pull/12527.

**Comment by pcattori** [comment]
I can't reproduce this locally. Could you share a repro on stackblitz or github?

**Comment by penspinner** [comment]
@pcattori I figured out that the issue occurs when the TS config has `composite: true`.

**Comment by dantrain** [comment]
@pcattori here's a [branch of the repo](https://github.com/dantrain/remix-relay/blob/update-react-router/apps/movie-app/app/routes/signin.tsx#L12) where I'm encountering this issue.

As @penspinner observed, it is happening when a redirect is returned from a loader/action. I don't seem to have `composite: true` in my tsconfig.

Presumably I could get around this by throwing the redirect instead of returning it, but the docs seem to encourage returning.

**Comment by stalexxx** [comment]
> @pcattori I figured out that the issue occurs when the `tsconfig.json.compilerOptions` has `composite: true`.

checked with both. Nothing changes

**Comment by 10xsai** [comment]
@pcattori Hi, facing same issue with RR7 as framework. When i am removing return from redirect, the error is going away. This is the exact message

```
Return type of exported function has or is using name 'redirectSymbol' from external module "/home/sai/MyProject/node_modules/.pnpm/react-router@7.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/route-data-aSUFWnQ6" but cannot be named.ts(4058)
```

**Comment by AdiRishi** [comment]
Experienced the same thing.

@pcattori if you want a very minimal reproduction repository, made one here - https://github.com/AdiRishi/rr7-redirect-ts-bug

The error can be seen by running `npm run typecheck` or going to the `app/routes/redirect-to-home.tsx` file.

**Comment by m-muiznieks** [comment]
I have exactly the same issue. :/

**Comment by pcattori** [comment]
@AdiRishi looking at your reproduction (https://github.com/AdiRishi/rr7-redirect-ts-bug), I commented out [`declaration`, `declarationMap`, and `sourceMap` from your `tsconfig.json`](https://github.com/AdiRishi/rr7-redirect-ts-bug/blob/main/tsconfig.json#L29-L31) since a React Router app is not a library and does not need generated type declarations. In fact, any settings of `tsconfig.json` that solely affect compilation output are irrelevant as React Router only uses `tsc` for typechecking and instead uses Vite for compilation.

That fixes the issue for me

**Comment by iamtomcat** [comment]
I'm currently running into this without any of those settings. I don't have a reproducible version at the moment. I'll try and make a version in the next few days.

**Comment by dantrain** [comment]
Thank you for looking into this @pcattori, I overrode these as you suggested and the problem is solved for me.

I wondered why I had added these library only options to my base `tsconfig.json` in the first place. It seems these are present in the boilerplate when setting up a monorepo using the [Turborepo](https://turbo.build/repo/docs/getting-started/installation) command `create-turbo@latest`, see [here](https://github.com/vercel/turborepo/blob/main/examples/basic/packages/typescript-config/base.json#L4). Hopefully this helps anyone with a similar issue.

**Comment by penspinner** [comment]
@pcattori

I tried setting `sourceMap`, `declaration`, and `declarationMap` to `false` in my `tsconfig.vite.json`. It's telling me that:

```
Composite projects may not disable declaration emit.
```

https://www.typescriptlang.org/tsconfig/#composite

<img width="544" alt="image" src="https://github.com/user-attachments/assets/9f05accf-15eb-4c2d-82dc-bfc5d3e14042" />

I'm using [project references](https://www.typescriptlang.org/docs/handbook/project-references.html#composite) and it requires `composite` setting to be enabled. TypeScript project references is used in the [Node Custom Server React Router template](https://github.com/remix-run/react-router-templates/tree/main/node-custom-server).

**Comment by jfsiii** [comment]
I have the same issue/constraint @penspinner mentioned. 

For now, I'm working around it using [the same code `react-router` does](https://github.com/remix-run/react-router/blob/6c2745357b464c0563700495d004d08a277a8925/packages/react-router/lib/router/utils.ts#L1383-L1398) but without the [problematic bit](https://github.com/remix-run/react-router/blob/6c2745357b464c0563700495d004d08a277a8925/packages/react-router/lib/router/utils.ts#L1374-L1375).

`Response.redirect(url, status)` works in most/simple cases but there are some times we're also passing other headers.

I also considered using `data(null, { headers: { location: url, status })` but since `react-router` is using `new Response` I stuck with that.

**Comment by jack-r-warren** [comment]
Also arrived here from the templates. A minimal reproduction:

```bash
npx create-react-router@latest ./reproduction \ 
  --template remix-run/react-router-templates/node-custom-server --yes
```

Edit `./reproduction/app/routes/home.tsx`:

```diff
+ import { redirect } from "react-router";
```

```diff
  export async function loader({ context }: Route.LoaderArgs) {
+   return redirect("example.org");
```

TypeScript error on `loader`:

> Return type of exported function has or is using name 'redirectSymbol' from external module "<redacted>/reproduction/node_modules/react-router/dist/development/route-data-aSUFWnQ6" but cannot be named. ts(4058)

**Comment by OscarAyoy** [comment]
The fix looks good from here! I'm now able to return a `redirect` as expected.

**Comment by OscarAyoy** [comment]
Returning a `redirect()` seems to be working as expected again!
